import org.apache.hadoop.security.proto.RefreshUserMappingsProtocolProtos.RefreshSuperUserGroupsConfigurationResponseProto;
public class FunctionUse15154 {
public void funcUse() {
RefreshSuperUserGroupsConfigurationResponseProto refreshsuperusergroupsconfigurationresponseproto = new RefreshSuperUserGroupsConfigurationResponseProto();
refreshsuperusergroupsconfigurationresponseproto.getDefaultInstance();
}
}